const l = "data:application/octet-stream;base64,PGxhYmVsIGNsYXNzPSJ7e2N0eC5pbnB1dC5sYWJlbENsYXNzfX0iPgogICAge3tjdHguaW5wdXQuY29udGVudH19CiAgICB7JSBpZiAoIWN0eC5zZWxmLmxhYmVsSXNIaWRkZW4oKSkgeyAlfTxzcGFuPnt7Y3R4LmlucHV0LmxhYmVsfX08L3NwYW4+eyUgfSAlfQo8L2xhYmVsPgo8ZGl2IHJlZj0idmFsdWUiPnslIGlmIChjdHguY2hlY2tlZCkgeyAlfVRydWV7JSB9IGVsc2UgeyAlfUZhbHNleyUgfSAlfTwvZGl2Pgo=";
export {
  l as default
};
//# sourceMappingURL=html.ejs.js.map
