"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = iconClass;
var iconMap = {
    'question-sign': 'question circle',
    'info-sign': 'info circle',
    'warning-sign': 'warning circle',
    'error-sign': 'times circle',
    'success-sign': 'check circle',
    'plus-sign': 'plus',
    'minus-sign': 'minus',
    'remove-sign': 'times',
    'ok-sign': 'check',
    search: 'search',
    calendar: 'calendar',
    clock: 'clock',
    time: 'clock',
    date: 'calendar',
    up: 'chevron up',
    down: 'chevron down',
    left: 'chevron left',
    right: 'chevron right',
    refresh: 'refresh',
    remove: 'times',
    clear: 'times',
    close: 'times',
    edit: 'pencil',
    save: 'save',
    delete: 'trash',
    add: 'plus',
    ok: 'check',
    cancel: 'times',
    upload: 'upload',
    download: 'download',
    'zoom-in': 'search plus',
    'zoom-out': 'search minus',
    filter: 'filter',
    sort: 'sort',
    'sort-up': 'sort up',
    'sort-down': 'sort down',
    menu: 'bars',
    list: 'list',
    home: 'home',
    user: 'user',
    users: 'users',
    lock: 'lock',
    unlock: 'unlock',
    key: 'key',
    cog: 'cog',
    gear: 'cog',
    wrench: 'wrench',
    heart: 'heart',
    star: 'star',
    link: 'link',
    unlink: 'unlink',
    paperclip: 'paperclip',
    pushpin: 'thumbtack',
    inbox: 'inbox',
    play: 'play',
    pause: 'pause',
    stop: 'stop',
    forward: 'forward',
    backward: 'backward',
    'fast-forward': 'fast forward',
    'fast-backward': 'fast backward',
    'step-forward': 'step forward',
    'step-backward': 'step backward',
    eject: 'eject',
    fullscreen: 'expand',
    'resize-full': 'expand',
    'resize-small': 'compress',
    phone: 'phone',
    'phone-alt': 'phone square',
    envelope: 'envelope',
    'envelope-alt': 'envelope square',
    comment: 'comment',
    comments: 'comments',
    'comment-alt': 'comment alternate',
    'comments-alt': 'comments alternate',
    eye: 'eye',
    'eye-close': 'eye slash',
    'eye-open': 'eye',
    camera: 'camera',
    'camera-retro': 'camera retro',
    picture: 'image',
    pencil: 'pencil',
    'map-marker': 'map marker',
    adjust: 'adjust',
    tint: 'tint',
    'edit-sign': 'pencil',
    'check-sign': 'check',
    check: 'check',
    'check-empty': 'square outline',
    'check-minus': 'minus square',
    'check-plus': 'plus square',
    'check-square': 'check square',
    circle: 'circle',
    'circle-blank': 'circle outline',
    'circle-arrow-left': 'arrow circle left',
    'circle-arrow-right': 'arrow circle right',
    'circle-arrow-up': 'arrow circle up',
    'circle-arrow-down': 'arrow circle down',
    'play-circle': 'play circle',
    'pause-circle': 'pause circle',
    'stop-circle': 'stop circle',
    'ban-circle': 'ban',
    'ok-circle': 'check circle',
    'remove-circle': 'times circle',
    'plus-circle': 'plus circle',
    'minus-circle': 'minus circle',
    'times-circle': 'times circle',
    'question-circle': 'question circle',
    'info-circle': 'info circle',
    'warning-circle': 'warning circle',
    'error-circle': 'times circle',
    'success-circle': 'check circle',
    plus: 'plus',
    minus: 'minus',
    times: 'times',
    question: 'question',
    info: 'info',
    warning: 'warning',
    error: 'times',
    success: 'check',
    'arrow-left': 'arrow left',
    'arrow-right': 'arrow right',
    'arrow-up': 'arrow up',
    'arrow-down': 'arrow down',
    'chevron-left': 'chevron left',
    'chevron-right': 'chevron right',
    'chevron-up': 'chevron up',
    'chevron-down': 'chevron down',
    'caret-left': 'caret left',
    'caret-right': 'caret right',
    'caret-up': 'caret up',
    'caret-down': 'caret down',
    'hand-left': 'hand point left',
    'hand-right': 'hand point right',
    'hand-up': 'hand point up',
    'hand-down': 'hand point down',
    move: 'arrows alternate',
    'resize-vertical': 'arrows alternate vertical',
    'resize-horizontal': 'arrows alternate horizontal',
    'fullscreen-alt': 'expand',
    'resize-full-alt': 'expand',
    'resize-small-alt': 'compress',
    'indent-left': 'indent',
    'indent-right': 'outdent',
    'list-ul': 'list ul',
    'list-ol': 'list ol',
    'list-alt': 'list alternate',
    'list-alt-ul': 'list alternate ul',
    'list-alt-ol': 'list alternate ol',
};
function iconClass(iconName) {
    return iconMap[iconName] || iconName;
}
