const l = {
  "question-sign": "question circle",
  "info-sign": "info circle",
  "warning-sign": "warning circle",
  "error-sign": "times circle",
  "success-sign": "check circle",
  "plus-sign": "plus",
  "minus-sign": "minus",
  "remove-sign": "times",
  "ok-sign": "check",
  search: "search",
  calendar: "calendar",
  clock: "clock",
  time: "clock",
  date: "calendar",
  up: "chevron up",
  down: "chevron down",
  left: "chevron left",
  right: "chevron right",
  refresh: "refresh",
  remove: "times",
  clear: "times",
  close: "times",
  edit: "pencil",
  save: "save",
  delete: "trash",
  add: "plus",
  ok: "check",
  cancel: "times",
  upload: "upload",
  download: "download",
  "zoom-in": "search plus",
  "zoom-out": "search minus",
  filter: "filter",
  sort: "sort",
  "sort-up": "sort up",
  "sort-down": "sort down",
  menu: "bars",
  list: "list",
  home: "home",
  user: "user",
  users: "users",
  lock: "lock",
  unlock: "unlock",
  key: "key",
  cog: "cog",
  gear: "cog",
  wrench: "wrench",
  heart: "heart",
  star: "star",
  link: "link",
  unlink: "unlink",
  paperclip: "paperclip",
  pushpin: "thumbtack",
  inbox: "inbox",
  play: "play",
  pause: "pause",
  stop: "stop",
  forward: "forward",
  backward: "backward",
  "fast-forward": "fast forward",
  "fast-backward": "fast backward",
  "step-forward": "step forward",
  "step-backward": "step backward",
  eject: "eject",
  fullscreen: "expand",
  "resize-full": "expand",
  "resize-small": "compress",
  phone: "phone",
  "phone-alt": "phone square",
  envelope: "envelope",
  "envelope-alt": "envelope square",
  comment: "comment",
  comments: "comments",
  "comment-alt": "comment alternate",
  "comments-alt": "comments alternate",
  eye: "eye",
  "eye-close": "eye slash",
  "eye-open": "eye",
  camera: "camera",
  "camera-retro": "camera retro",
  picture: "image",
  pencil: "pencil",
  "map-marker": "map marker",
  adjust: "adjust",
  tint: "tint",
  "edit-sign": "pencil",
  "check-sign": "check",
  check: "check",
  "check-empty": "square outline",
  "check-minus": "minus square",
  "check-plus": "plus square",
  "check-square": "check square",
  circle: "circle",
  "circle-blank": "circle outline",
  "circle-arrow-left": "arrow circle left",
  "circle-arrow-right": "arrow circle right",
  "circle-arrow-up": "arrow circle up",
  "circle-arrow-down": "arrow circle down",
  "play-circle": "play circle",
  "pause-circle": "pause circle",
  "stop-circle": "stop circle",
  "ban-circle": "ban",
  "ok-circle": "check circle",
  "remove-circle": "times circle",
  "plus-circle": "plus circle",
  "minus-circle": "minus circle",
  "times-circle": "times circle",
  "question-circle": "question circle",
  "info-circle": "info circle",
  "warning-circle": "warning circle",
  "error-circle": "times circle",
  "success-circle": "check circle",
  plus: "plus",
  minus: "minus",
  times: "times",
  question: "question",
  info: "info",
  warning: "warning",
  error: "times",
  success: "check",
  "arrow-left": "arrow left",
  "arrow-right": "arrow right",
  "arrow-up": "arrow up",
  "arrow-down": "arrow down",
  "chevron-left": "chevron left",
  "chevron-right": "chevron right",
  "chevron-up": "chevron up",
  "chevron-down": "chevron down",
  "caret-left": "caret left",
  "caret-right": "caret right",
  "caret-up": "caret up",
  "caret-down": "caret down",
  "hand-left": "hand point left",
  "hand-right": "hand point right",
  "hand-up": "hand point up",
  "hand-down": "hand point down",
  move: "arrows alternate",
  "resize-vertical": "arrows alternate vertical",
  "resize-horizontal": "arrows alternate horizontal",
  "fullscreen-alt": "expand",
  "resize-full-alt": "expand",
  "resize-small-alt": "compress",
  "indent-left": "indent",
  "indent-right": "outdent",
  "list-ul": "list ul",
  "list-ol": "list ol",
  "list-alt": "list alternate",
  "list-alt-ul": "list alternate ul",
  "list-alt-ol": "list alternate ol",
  "list-alt-ul-alt": "list alternate ul",
  "list-alt-ol-alt": "list alternate ol",
  "list-alt-ul-alt-2": "list alternate ul",
  "list-alt-ol-alt-2": "list alternate ol",
  "list-alt-ul-alt-3": "list alternate ul",
  "list-alt-ol-alt-3": "list alternate ol",
  "list-alt-ul-alt-4": "list alternate ul",
  "list-alt-ol-alt-4": "list alternate ol",
  "list-alt-ul-alt-5": "list alternate ul",
  "list-alt-ol-alt-5": "list alternate ol",
  "list-alt-ul-alt-6": "list alternate ul",
  "list-alt-ol-alt-6": "list alternate ol",
  "list-alt-ul-alt-7": "list alternate ul",
  "list-alt-ol-alt-7": "list alternate ol",
  "list-alt-ul-alt-8": "list alternate ul",
  "list-alt-ol-alt-8": "list alternate ol",
  "list-alt-ul-alt-9": "list alternate ul",
  "list-alt-ol-alt-9": "list alternate ol",
  "list-alt-ul-alt-10": "list alternate ul",
  "list-alt-ol-alt-10": "list alternate ol",
  "list-alt-ul-alt-11": "list alternate ul",
  "list-alt-ol-alt-11": "list alternate ol",
  "list-alt-ul-alt-12": "list alternate ul",
  "list-alt-ol-alt-12": "list alternate ol",
  "list-alt-ul-alt-13": "list alternate ul",
  "list-alt-ol-alt-13": "list alternate ol",
  "list-alt-ul-alt-14": "list alternate ul",
  "list-alt-ol-alt-14": "list alternate ol",
  "list-alt-ul-alt-15": "list alternate ul",
  "list-alt-ol-alt-15": "list alternate ol",
  "list-alt-ul-alt-16": "list alternate ul",
  "list-alt-ol-alt-16": "list alternate ol",
  "list-alt-ul-alt-17": "list alternate ul",
  "list-alt-ol-alt-17": "list alternate ol",
  "list-alt-ul-alt-18": "list alternate ul",
  "list-alt-ol-alt-18": "list alternate ol",
  "list-alt-ul-alt-19": "list alternate ul",
  "list-alt-ol-alt-19": "list alternate ol",
  "list-alt-ul-alt-20": "list alternate ul",
  "list-alt-ol-alt-20": "list alternate ol",
  "list-alt-ul-alt-21": "list alternate ul",
  "list-alt-ol-alt-21": "list alternate ol",
  "list-alt-ul-alt-22": "list alternate ul",
  "list-alt-ol-alt-22": "list alternate ol",
  "list-alt-ul-alt-23": "list alternate ul",
  "list-alt-ol-alt-23": "list alternate ol",
  "list-alt-ul-alt-24": "list alternate ul",
  "list-alt-ol-alt-24": "list alternate ol",
  "list-alt-ul-alt-25": "list alternate ul",
  "list-alt-ol-alt-25": "list alternate ol",
  "list-alt-ul-alt-26": "list alternate ul",
  "list-alt-ol-alt-26": "list alternate ol",
  "list-alt-ul-alt-27": "list alternate ul",
  "list-alt-ol-alt-27": "list alternate ol",
  "list-alt-ul-alt-28": "list alternate ul",
  "list-alt-ol-alt-28": "list alternate ol",
  "list-alt-ul-alt-29": "list alternate ul",
  "list-alt-ol-alt-29": "list alternate ol",
  "list-alt-ul-alt-30": "list alternate ul",
  "list-alt-ol-alt-30": "list alternate ol",
  "list-alt-ul-alt-31": "list alternate ul",
  "list-alt-ol-alt-31": "list alternate ol",
  "list-alt-ul-alt-32": "list alternate ul",
  "list-alt-ol-alt-32": "list alternate ol",
  "list-alt-ul-alt-33": "list alternate ul",
  "list-alt-ol-alt-33": "list alternate ol",
  "list-alt-ul-alt-34": "list alternate ul",
  "list-alt-ol-alt-34": "list alternate ol",
  "list-alt-ul-alt-35": "list alternate ul",
  "list-alt-ol-alt-35": "list alternate ol",
  "list-alt-ul-alt-36": "list alternate ul",
  "list-alt-ol-alt-36": "list alternate ol",
  "list-alt-ul-alt-37": "list alternate ul",
  "list-alt-ol-alt-37": "list alternate ol",
  "list-alt-ul-alt-38": "list alternate ul",
  "list-alt-ol-alt-38": "list alternate ol",
  "list-alt-ul-alt-39": "list alternate ul",
  "list-alt-ol-alt-39": "list alternate ol",
  "list-alt-ul-alt-40": "list alternate ul",
  "list-alt-ol-alt-40": "list alternate ol",
  "list-alt-ul-alt-41": "list alternate ul",
  "list-alt-ol-alt-41": "list alternate ol",
  "list-alt-ul-alt-42": "list alternate ul",
  "list-alt-ol-alt-42": "list alternate ol",
  "list-alt-ul-alt-43": "list alternate ul",
  "list-alt-ol-alt-43": "list alternate ol",
  "list-alt-ul-alt-44": "list alternate ul",
  "list-alt-ol-alt-44": "list alternate ol",
  "list-alt-ul-alt-45": "list alternate ul",
  "list-alt-ol-alt-45": "list alternate ol",
  "list-alt-ul-alt-46": "list alternate ul",
  "list-alt-ol-alt-46": "list alternate ol",
  "list-alt-ul-alt-47": "list alternate ul",
  "list-alt-ol-alt-47": "list alternate ol",
  "list-alt-ul-alt-48": "list alternate ul",
  "list-alt-ol-alt-48": "list alternate ol",
  "list-alt-ul-alt-49": "list alternate ul",
  "list-alt-ol-alt-49": "list alternate ol",
  "list-alt-ul-alt-50": "list alternate ul",
  "list-alt-ol-alt-50": "list alternate ol",
  "list-alt-ul-alt-51": "list alternate ul",
  "list-alt-ol-alt-51": "list alternate ol",
  "list-alt-ul-alt-52": "list alternate ul",
  "list-alt-ol-alt-52": "list alternate ol",
  "list-alt-ul-alt-53": "list alternate ul",
  "list-alt-ol-alt-53": "list alternate ol",
  "list-alt-ul-alt-54": "list alternate ul",
  "list-alt-ol-alt-54": "list alternate ol",
  "list-alt-ul-alt-55": "list alternate ul",
  "list-alt-ol-alt-55": "list alternate ol",
  "list-alt-ul-alt-56": "list alternate ul",
  "list-alt-ol-alt-56": "list alternate ol",
  "list-alt-ul-alt-57": "list alternate ul",
  "list-alt-ol-alt-57": "list alternate ol",
  "list-alt-ul-alt-58": "list alternate ul",
  "list-alt-ol-alt-58": "list alternate ol",
  "list-alt-ul-alt-59": "list alternate ul",
  "list-alt-ol-alt-59": "list alternate ol",
  "list-alt-ul-alt-60": "list alternate ul",
  "list-alt-ol-alt-60": "list alternate ol",
  "list-alt-ul-alt-61": "list alternate ul",
  "list-alt-ol-alt-61": "list alternate ol",
  "list-alt-ul-alt-62": "list alternate ul",
  "list-alt-ol-alt-62": "list alternate ol",
  "list-alt-ul-alt-63": "list alternate ul",
  "list-alt-ol-alt-63": "list alternate ol",
  "list-alt-ul-alt-64": "list alternate ul",
  "list-alt-ol-alt-64": "list alternate ol",
  "list-alt-ul-alt-65": "list alternate ul",
  "list-alt-ol-alt-65": "list alternate ol",
  "list-alt-ul-alt-66": "list alternate ul",
  "list-alt-ol-alt-66": "list alternate ol",
  "list-alt-ul-alt-67": "list alternate ul",
  "list-alt-ol-alt-67": "list alternate ol",
  "list-alt-ul-alt-68": "list alternate ul",
  "list-alt-ol-alt-68": "list alternate ol",
  "list-alt-ul-alt-69": "list alternate ul",
  "list-alt-ol-alt-69": "list alternate ol",
  "list-alt-ul-alt-70": "list alternate ul",
  "list-alt-ol-alt-70": "list alternate ol",
  "list-alt-ul-alt-71": "list alternate ul",
  "list-alt-ol-alt-71": "list alternate ol",
  "list-alt-ul-alt-72": "list alternate ul",
  "list-alt-ol-alt-72": "list alternate ol",
  "list-alt-ul-alt-73": "list alternate ul",
  "list-alt-ol-alt-73": "list alternate ol",
  "list-alt-ul-alt-74": "list alternate ul",
  "list-alt-ol-alt-74": "list alternate ol",
  "list-alt-ul-alt-75": "list alternate ul",
  "list-alt-ol-alt-75": "list alternate ol",
  "list-alt-ul-alt-76": "list alternate ul",
  "list-alt-ol-alt-76": "list alternate ol",
  "list-alt-ul-alt-77": "list alternate ul",
  "list-alt-ol-alt-77": "list alternate ol",
  "list-alt-ul-alt-78": "list alternate ul",
  "list-alt-ol-alt-78": "list alternate ol",
  "list-alt-ul-alt-79": "list alternate ul",
  "list-alt-ol-alt-79": "list alternate ol",
  "list-alt-ul-alt-80": "list alternate ul",
  "list-alt-ol-alt-80": "list alternate ol",
  "list-alt-ul-alt-81": "list alternate ul",
  "list-alt-ol-alt-81": "list alternate ol",
  "list-alt-ul-alt-82": "list alternate ul",
  "list-alt-ol-alt-82": "list alternate ol",
  "list-alt-ul-alt-83": "list alternate ul",
  "list-alt-ol-alt-83": "list alternate ol",
  "list-alt-ul-alt-84": "list alternate ul",
  "list-alt-ol-alt-84": "list alternate ol",
  "list-alt-ul-alt-85": "list alternate ul",
  "list-alt-ol-alt-85": "list alternate ol",
  "list-alt-ul-alt-86": "list alternate ul",
  "list-alt-ol-alt-86": "list alternate ol",
  "list-alt-ul-alt-87": "list alternate ul",
  "list-alt-ol-alt-87": "list alternate ol",
  "list-alt-ul-alt-88": "list alternate ul",
  "list-alt-ol-alt-88": "list alternate ol",
  "list-alt-ul-alt-89": "list alternate ul",
  "list-alt-ol-alt-89": "list alternate ol",
  "list-alt-ul-alt-90": "list alternate ul",
  "list-alt-ol-alt-90": "list alternate ol",
  "list-alt-ul-alt-91": "list alternate ul",
  "list-alt-ol-alt-91": "list alternate ol",
  "list-alt-ul-alt-92": "list alternate ul",
  "list-alt-ol-alt-92": "list alternate ol",
  "list-alt-ul-alt-93": "list alternate ul",
  "list-alt-ol-alt-93": "list alternate ol",
  "list-alt-ul-alt-94": "list alternate ul",
  "list-alt-ol-alt-94": "list alternate ol",
  "list-alt-ul-alt-95": "list alternate ul",
  "list-alt-ol-alt-95": "list alternate ol",
  "list-alt-ul-alt-96": "list alternate ul",
  "list-alt-ol-alt-96": "list alternate ol",
  "list-alt-ul-alt-97": "list alternate ul",
  "list-alt-ol-alt-97": "list alternate ol",
  "list-alt-ul-alt-98": "list alternate ul",
  "list-alt-ol-alt-98": "list alternate ol",
  "list-alt-ul-alt-99": "list alternate ul",
  "list-alt-ol-alt-99": "list alternate ol",
  "list-alt-ul-alt-100": "list alternate ul",
  "list-alt-ol-alt-100": "list alternate ol"
};
export {
  l as default
};
//# sourceMappingURL=iconClass.js.map
