interface GoFormsTemplate {
    transform: (type: string, text: string | number) => string;
    defaultIconset: string;
    iconClass: (iconset: string, name: string, spinning?: boolean) => string;
    cssClasses: Record<string, string>;
    builder: unknown;
    builderComponent: unknown;
    builderComponents: unknown;
    builderEditForm: unknown;
    builderPlaceholder: unknown;
    builderSidebar: unknown;
    builderSidebarGroup: unknown;
    builderWizard: unknown;
    button: unknown;
    checkbox: unknown;
    columns: unknown;
    component: unknown;
    datagrid: unknown;
    day: unknown;
    editgrid: unknown;
    field: unknown;
    fieldset: unknown;
    file: unknown;
    icon: unknown;
    input: unknown;
    label: unknown;
    loader: unknown;
    loading: unknown;
    message: unknown;
    multiValueRow: unknown;
    multiValueTable: unknown;
    panel: unknown;
    radio: unknown;
    resourceAdd: unknown;
    select: unknown;
    selectOption: unknown;
    signature: unknown;
    survey: unknown;
    tab: unknown;
    tree: unknown;
    treeEdit: unknown;
    treeView: unknown;
    table: unknown;
    webform: unknown;
    well: unknown;
    wizard: unknown;
    wizardHeader: unknown;
    wizardHeaderClassic: unknown;
    wizardHeaderVertical: unknown;
    wizardNav: unknown;
    alert: unknown;
    errorsList: unknown;
}
declare const goforms: GoFormsTemplate;
export default goforms;
