"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    // Base classes
    'form-component': 'form-component',
    'form-components': 'form-components',
    'form-container': 'form-container',
    // Field classes
    'form-field-wrapper': 'form-field-wrapper',
    'form-field-wrapper-reverse': 'form-field-wrapper--reverse',
    'form-field-label': 'form-field-label',
    'form-field-label-right': 'form-field-label--right',
    'form-field-hidden-label': 'form-field-hidden-label',
    'form-field-content': 'form-field-content',
    'form-field-description': 'form-field-description',
    // HTML Element classes
    'form-html-element': 'form-html-element',
    'form-html-element-content': 'form-html-element-content',
    // Icon classes
    'form-icon': 'form-icon',
    'form-icon-content': 'form-icon-content',
    // Label classes
    'form-label': 'form-label',
    'form-label-required': 'form-label--required',
    'form-label-tooltip': 'form-label-tooltip',
    // Loader classes
    'form-loader': 'form-loader',
    'form-loader-spinner': 'form-loader-spinner',
    'form-loader-content': 'form-loader-content',
    // Loading classes
    'form-loading': 'form-loading',
    'form-loading-overlay': 'form-loading-overlay',
    'form-loading-spinner': 'form-loading-spinner',
    // Map classes
    'form-map': 'form-map',
    'form-map-container': 'form-map-container',
    'form-map-search': 'form-map-search',
    'form-map-results': 'form-map-results',
    // Message classes
    'form-message': 'form-message',
    'form-message-error': 'form-message--error',
    'form-message-success': 'form-message--success',
    'form-message-warning': 'form-message--warning',
    'form-message-info': 'form-message--info',
    // Modal classes
    'form-modal': 'form-modal',
    'form-modal-dialog': 'form-modal-dialog',
    'form-modal-content': 'form-modal-content',
    'form-modal-header': 'form-modal-header',
    'form-modal-title': 'form-modal-title',
    'form-modal-body': 'form-modal-body',
    'form-modal-footer': 'form-modal-footer',
    'form-modal-close': 'form-modal-close',
    'form-modal-backdrop': 'form-modal-backdrop',
    'form-modal-edit': 'form-modal-edit',
    'form-modal-preview-button': 'form-modal-preview-button',
    // Multi-value classes
    'form-multi-value': 'form-multi-value',
    'form-multi-value-row': 'form-multi-value-row',
    'form-multi-value-table': 'form-multi-value-table',
    'form-multi-value-input': 'form-multi-value-input',
    'form-multi-value-remove': 'form-multi-value-remove',
    'form-multi-value-add': 'form-multi-value-add',
    'form-multi-value-select': 'form-multi-value-select',
    // Panel classes
    'form-panel': 'form-panel',
    'form-panel-header': 'form-panel-header',
    'form-panel-title': 'form-panel-title',
    'form-panel-body': 'form-panel-body',
    'form-panel-footer': 'form-panel-footer',
    // PDF classes
    'form-pdf': 'form-pdf',
    'form-pdf-container': 'form-pdf-container',
    'form-pdf-viewer': 'form-pdf-viewer',
    'form-pdf-toolbar': 'form-pdf-toolbar',
    'form-pdf-builder': 'form-pdf-builder',
    'form-pdf-builder-upload': 'form-pdf-builder-upload',
    'form-pdf-builder-preview': 'form-pdf-builder-preview',
    // Radio classes
    'form-radio': 'form-radio',
    'form-radio-input': 'form-radio-input',
    'form-radio-label': 'form-radio-label',
    'form-radio-group': 'form-radio-group',
    // Resource classes
    'form-resource': 'form-resource',
    'form-resource-add': 'form-resource-add',
    'form-resource-select': 'form-resource-select',
    'form-resource-search': 'form-resource-search',
    // Wizard classes
    'form-wizard': 'form-wizard',
    'form-wizard-container': 'form-wizard-container',
    'form-wizard-vertical': 'form-wizard-vertical',
    'form-wizard-horizontal': 'form-wizard-horizontal',
    'form-wizard-sidebar': 'form-wizard-sidebar',
    'form-wizard-content': 'form-wizard-content',
    'form-wizard-navigation-container': 'form-wizard-navigation-container',
    'form-wizard-navigation-right': 'form-wizard-navigation-right',
    'form-wizard-header': 'form-wizard-header',
    'form-wizard-pages': 'form-wizard-pages',
    'form-wizard-page': 'form-wizard-page',
    'form-wizard-page-active': 'form-wizard-page-active',
    'form-wizard-page-link': 'form-wizard-page-link',
    'form-wizard-page-tooltip': 'form-wizard-page-tooltip',
    'form-wizard-navigation': 'form-wizard-navigation',
    'form-wizard-navigation-item': 'form-wizard-navigation-item',
    'form-wizard-navigation-button': 'form-wizard-navigation-button',
    'form-wizard-navigation-cancel': 'form-wizard-navigation-cancel',
    'form-wizard-navigation-previous': 'form-wizard-navigation-previous',
    'form-wizard-navigation-next': 'form-wizard-navigation-next',
    'form-wizard-navigation-submit': 'form-wizard-navigation-submit',
    // Input classes
    'form-input': 'form-input',
    'form-input-group': 'form-input-group',
    'form-input-prefix': 'form-input-prefix',
    'form-input-suffix': 'form-input-suffix',
    'form-input-floating': 'form-input-floating',
    'form-input-label': 'form-input-label',
    'form-input-mask': 'form-input-mask',
    'form-input-editor': 'form-input-editor',
    'form-input-counts': 'form-input-counts',
    'form-input-char-count': 'form-input-char-count',
    'form-input-word-count': 'form-input-word-count',
    'form-input-value': 'form-input-value',
    // Button classes
    'form-button': 'form-button',
    'form-button-default': 'form-button-default',
    'form-button-primary': 'form-button-primary',
    'form-button-secondary': 'form-button-secondary',
    'form-button-success': 'form-button-success',
    'form-button-danger': 'form-button-danger',
    'form-button-warning': 'form-button-warning',
    'form-button-info': 'form-button-info',
    'form-button-sm': 'form-button-sm',
    'form-button-md': 'form-button-md',
    'form-button-lg': 'form-button-lg',
    'form-button-block': 'form-button-block',
    'form-button-icon': 'form-button-icon',
    'form-button-icon-left': 'form-button-icon-left',
    'form-button-icon-right': 'form-button-icon-right',
    'form-button-content': 'form-button-content',
    'form-button-tooltip': 'form-button-tooltip',
    'form-button-message': 'form-button-message',
    'form-button-value': 'form-button-value',
    // Checkbox classes
    'form-checkbox': 'form-checkbox',
    'form-checkbox-input': 'form-checkbox-input',
    'form-checkbox-label': 'form-checkbox-label',
    'form-checkbox-tooltip': 'form-checkbox-tooltip',
    'form-checkbox-value': 'form-checkbox-value',
    // Columns classes
    'form-columns-col': 'form-columns-col',
    'form-columns-col-offset': 'form-columns-col-offset',
    // Component classes
    'form-component-children': 'form-component-children',
    'form-component-errors': 'form-component-errors',
    // Builder classes
    'form-builder': 'form-builder',
    'form-builder-sidebar': 'form-builder-sidebar',
    'form-builder-area': 'form-builder-area',
    'form-builder-component': 'form-builder-component',
    'form-builder-component-header': 'form-builder-component-header',
    'form-builder-component-title': 'form-builder-component-title',
    'form-builder-component-actions': 'form-builder-component-actions',
    'form-builder-component-edit': 'form-builder-component-edit',
    'form-builder-component-remove': 'form-builder-component-remove',
    'form-builder-component-content': 'form-builder-component-content',
    'form-builder-components': 'form-builder-components',
    'form-builder-component-group': 'form-builder-component-group',
    'form-builder-component-group-title': 'form-builder-component-group-title',
    'form-builder-component-group-items': 'form-builder-component-group-items',
    'form-builder-component-item': 'form-builder-component-item',
    'form-builder-edit': 'form-builder-edit',
    'form-builder-edit-header': 'form-builder-edit-header',
    'form-builder-edit-title': 'form-builder-edit-title',
    'form-builder-edit-close': 'form-builder-edit-close',
    'form-builder-edit-content': 'form-builder-edit-content',
    'form-builder-edit-tabs': 'form-builder-edit-tabs',
    'form-builder-edit-tab': 'form-builder-edit-tab',
    'form-builder-edit-panel': 'form-builder-edit-panel',
    'form-builder-edit-footer': 'form-builder-edit-footer',
    'form-builder-edit-cancel': 'form-builder-edit-cancel',
    'form-builder-edit-save': 'form-builder-edit-save',
    'form-builder-placeholder': 'form-builder-placeholder',
    'form-builder-placeholder-content': 'form-builder-placeholder-content',
    'form-builder-sidebar-group': 'form-builder-sidebar-group',
    'form-builder-sidebar-group-header': 'form-builder-sidebar-group-header',
    'form-builder-sidebar-group-toggle': 'form-builder-sidebar-group-toggle',
    'form-builder-sidebar-group-content': 'form-builder-sidebar-group-content',
    'form-builder-sidebar-group-items': 'form-builder-sidebar-group-items',
    'form-builder-sidebar-component': 'form-builder-sidebar-component',
    'form-builder-sidebar-no-matches': 'form-builder-sidebar-no-matches',
    'form-builder-wizard': 'form-builder-wizard',
    'form-builder-wizard-main': 'form-builder-wizard-main',
    // Legacy classes (for backward compatibility)
    'border-default': '',
    'formio-tab-panel-active': 'active',
    'formio-tab-link-active': 'active',
    'formio-tab-link-container-active': 'active',
    'formio-form-error': 'formio-error-wrapper has-message',
    'formio-form-alert': 'alert alert-danger',
    'formio-label-error': '',
    'formio-input-error': '',
    'formio-alert-danger': 'alert alert-danger',
    'formio-alert-success': 'alert alert-success',
    'formio-alert-warning': 'alert alert-warning',
    'formio-modal-cancel-button': 'btn btn-danger formio-dialog-button',
    'formio-modal-confirm-button': 'btn btn-primary formio-dialog-button',
    'form-group': 'formio-form-group',
};
